" vim:ts=2:sts=2:sw=2:et:nowrap
"
syntax on
filetype plugin indent on

"== Plugin Setup ===============================================================

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()

" Plugin management
Plug 'junegunn/vim-plug'

" LSP
Plug 'neoclide/coc.nvim',                          { 'branch': 'release' }
"Plug 'neoclide/coc-highlight',                     { 'do': 'yarn install --frozen-lockfile && yarn build' }
"
" Visuals
Plug 'arcticicestudio/nord-vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" General-purpose
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
"Plug 'scrooloose/nerdtree'
Plug 'luochen1990/rainbow'
Plug 'tpope/vim-surround'
Plug 'milkypostman/vim-togglelist'
Plug 'vim-scripts/AnsiEsc.vim'
Plug 'junegunn/vim-easy-align'

" vim customization + features
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-projectionist'

" clojure support
Plug 'NoahTheDuke/coc-clojure',                    { 'for': 'clojure' }
Plug 'tpope/vim-fireplace',                        { 'for': 'clojure' }
Plug 'tpope/vim-salve',                            { 'for': 'clojure' }
Plug 'tpope/vim-classpath',                        { 'for': 'clojure' }
Plug 'guns/vim-sexp',                              { 'for': 'clojure' }
Plug 'tpope/vim-sexp-mappings-for-regular-people', { 'for': 'clojure' }
Plug 'clojure-vim/vim-jack-in',                    { 'for': 'clojure' }

" scala support
Plug 'derekwyatt/vim-scala',                       { 'for': 'scala' }

call plug#end()

let g:salve_auto_start_repl=1

let g:fzf_command_prefix = 'Fz'

let g:airline_theme='nord'
let g:airline_powerline_fonts=1
let g:nord_bold_vertical_split_line=1

let g:rainbow_active = 1

let NERDTreeKeepTreeInNewTab=1

let g:mapleader=' '
let g:maplocalleader=','

" Use tab for trigger completion with characters ahead and navigate
" NOTE: There's always complete item selected by default, you may want to enable
" no select by `"suggest.noselect": true` in your configuration file
" NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
" other plugin before putting this into your config
inoremap <silent><expr> <TAB>
      \ coc#pum#visible() ? coc#pum#next(1) :
      \ CheckBackspace() ? "\<Tab>" :
      \ coc#refresh()
inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"

" Make <CR> to accept selected completion item or notify coc.nvim to format
" <C-g>u breaks current undo, please make your own choice
inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
      \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

function! CheckBackspace() abort
    let col = col('.') - 1
      return !col || getline('.')[col - 1]  =~# '\s'
endfunction

"== General Setup ==============================================================

" Disable annoying bell sounds
set belloff=all

" Disable BCE to make colorschemes work on tmux
set t_ut=
set t_Co=256
"set termguicolors
colorscheme nord

" Use all utf-8 for encoding a file.
scriptencoding utf-8
set fileencodings=utf-8,utf-16le,utf-16be
set encoding=utf-8

set textwidth=120
if &diff
  set winwidth=5
  set diffopt+=iwhite
else
  set foldmethod=syntax
  set foldlevelstart=99
  set winwidth=121
  set colorcolumn=+1
endif

set scrollopt+=hor

" Default indent style
set tabstop=2 shiftwidth=2 softtabstop=2 expandtab

" UTF-8 Visual aids setup.
set showbreak=>\ 
set fillchars=vert:│,stl:-
set list
set listchars=tab:\|-,trail:~,eol:$,space:·
nmap <silent> <F9> :set list!<CR>

set nowrap
set fo-=t " Don't format text automatically using textwidth
set bs=indent,eol,start
set ignorecase
set virtualedit=onemore
set modelines=5

" Highlight current cursor line
set cul

set scrolloff=999

"= Line number display Setup ===================================================

" default to relative line numbers
set signcolumn=yes
set relativenumber
set number
set numberwidth=5

" show absolute line numbers when focus is lost
au FocusLost *   :set nu | set nornu
au FocusGained * :set rnu | set nu

" show absolute line numbers when in insert mode
au InsertEnter * :set nu | set nornu
au InsertLeave * :set rnu | set nu

nmap <silent> <leader>i"gu i=system("uuidgen \| tr -d '\n' \| tr '[:upper:]' '[:lower:]'")<CR><Esc>
nmap <silent> <leader>igu i"=system("uuidgen \| tr -d '\n' \| tr '[:upper:]' '[:lower:]'")<CR>"<Esc>
nmap <silent> <leader>ci"u ci"=system("uuidgen \| tr -d '\n' \| tr '[:upper:]' '[:lower:]'")<CR><Esc>

nmap <silent> <leader>/g :FzGit<cr>
nmap <silent> <leader>// :FZF<CR>
nmap <silent> <leader>/c :FzAg<CR>

nmap <silent> <leader>t" :bo term<CR>

nmap <silent> <F3> :NERDTreeToggle<CR>
nmap <silent> <F4> :NERDTreeFind<CR>

nmap <silent> <F7> :AnsiEsc<CR>
nmap <silent> <F8> :RainbowToggle<CR>

"nnoremap <Plug>(coc-codeaction)
"nnoremap <Plug>(coc-codeaction-cursor)
"nnoremap <Plug>(coc-codeaction-line)
"nnoremap <Plug>(coc-codeaction-refactor)
"nnoremap <Plug>(coc-codeaction-refactor-selected)
"nnoremap <Plug>(coc-codeaction-selected)
"nnoremap <Plug>(coc-codeaction-source)
"nnoremap <Plug>(coc-codelens-action)
"nnoremap <Plug>(coc-range-select)
"nnoremap <silent> <Plug>(coc-command-repeat)
"nnoremap <silent> <Plug>(coc-cursors-operator)
"nnoremap <silent> <Plug>(coc-cursors-position)
"nnoremap <silent> <Plug>(coc-cursors-word)
"nnoremap <silent> <Plug>(coc-declaration)
"nnoremap <silent> <Plug>(coc-definition)
"nnoremap <silent> <Plug>(coc-diagnostic-info)
"nnoremap <silent> <Plug>(coc-diagnostic-next)
"nnoremap <silent> <Plug>(coc-diagnostic-next-error)
"nnoremap <silent> <Plug>(coc-diagnostic-prev)
"nnoremap <silent> <Plug>(coc-diagnostic-prev-error)
"nnoremap <silent> <Plug>(coc-fix-current)
"nnoremap <silent> <Plug>(coc-float-hide)
"nnoremap <silent> <Plug>(coc-float-jump)
"nnoremap <silent> <Plug>(coc-format)
"nnoremap <silent> <Plug>(coc-format-selected)
"nnoremap <silent> <Plug>(coc-implementation)
"nnoremap <silent> <Plug>(coc-openlink)
"nnoremap <silent> <Plug>(coc-refactor)
"nnoremap <silent> <Plug>(coc-references)
"nnoremap <silent> <Plug>(coc-references-used)
"nnoremap <silent> <Plug>(coc-rename)
"nnoremap <silent> <Plug>(coc-type-definition)
"onoremap <silent> <Plug>(coc-classobj-a)
"onoremap <silent> <Plug>(coc-classobj-i)
"onoremap <silent> <Plug>(coc-funcobj-a)
"onoremap <silent> <Plug>(coc-funcobj-i)
"vnoremap <Plug>(coc-codeaction-refactor-selected)
"vnoremap <silent> <Plug>(coc-classobj-a)
"vnoremap <silent> <Plug>(coc-classobj-i)
"vnoremap <silent> <Plug>(coc-codeaction-selected)
"vnoremap <silent> <Plug>(coc-cursors-range)
"vnoremap <silent> <Plug>(coc-format-selected)
"vnoremap <silent> <Plug>(coc-funcobj-a)
"vnoremap <silent> <Plug>(coc-funcobj-i)
"vnoremap <silent> <Plug>(coc-range-select)
"vnoremap <silent> <Plug>(coc-range-select-backward)
